@startuml

package "Commons" {
[CommonAudioInfo]
[InputDeviceInfo]
[Settings]
[First Component]
}

package "Engine" {
[Audio]<|--[StaticAudio]
[Audio]<|--[LiveAudio]
[ProcessingEngine]->[InterpretEngine]
[Converter]
[Ear]
}


package "StreamHandlers" {
    [Stream]
}

package "UI" {
    [Stream]
    [OutputStream]
}

Engine -> Commons : uses
StreamHandlers -> Commons : uses
@enduml