@startuml

package "Commons" {
[CommonAudioInfo]
[InputDeviceInfo]
[Settings]
}

package "Engine" {
[Audio]<|--[StaticAudio]
[Audio]<|--[LiveAudio]
[ProcessingEngine]->[InterpretEngine]
[Converter]
[Ear]
}
Engine -> Commons : uses

package "StreamHandlers" {
    [Stream]
}
StreamHandlers -> Commons : uses
package "UI" {
    [Stream]
    [OutputStream]
}



@enduml