@startuml


[User Interface] <- [Interpret Engine] : Event
[Interpret Engine] -> [ProcessingEngine] : Observes for data

[ProcessingEngine] ..> [AudioFile] : Uses
[ProcessingEngine] -> [Ear] : Observes

[Ear] -> [OutputStream] : Event
[Ear] -> [Stream] : Observes

[Stream] <- mic
[OutputStream] -> speaker_headphones
@enduml