@startuml
(*)  --> [PCM]"Stream"
-->  "ProcessingEngine"
--> [passes LiveAudio reference]"InterpretEngine"
"Stream"-->"OutputStream"
"OutputStream"-->(*)

partition MessageServer #LightSkyBlue {
  "Stream" --> "MessageServer"
  "ProcessingEngine" --> "MessageServer"
  "InterpretEngine" -->   [         ?       ]"MessageServer"
}
"MessageServer" --> "UI"
"MessageServer" --> "ProcessingEngine"
"MessageServer" --> "OutputStream"
@enduml